name: test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: "ref branch for this workflow"
        default: "master"
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  test-docker-archlinux-x64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.1
      with:
        ref: ${{ inputs.branch }}
    - name: Build, Test units and Integration tests
      uses: addnab/docker-run-action@v3
      with:
        image: archlinux
        options: --volume ${{ github.workspace }}:/work --workdir /work --privileged --env CARGO_TERM_COLOR=always
        run: |
          set -e
          echo "::group::Install Prerequisites"
            bin/install_prerequisites_archlinux.sh
          echo "::endgroup::"
          echo "::group::Install python3 venv"
            bin/install_python3_venv.sh
            export PATH=/tmp/hurl-python3-venv/bin:$PATH
            which python3
            python3 --version
            pip --version
          echo "::endgroup::"
          echo "::group::Install Rust"
            bin/install_rust.sh
          echo "::endgroup::"
          echo "::group::Environment"
            bin/environment.sh
          echo "::endgroup::"
          echo "::group::Tests"
            bin/test/test.sh
          echo "::endgroup::"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4.4.3
      if: ${{ always() }}
      with:
        name: tests-archlinux-x64-artifacts
        path: |
          ./**/*.log

  test-windows-wsl2-x64:
    runs-on: windows-latest
    steps:
    - name: Setup WSL
      uses: Vampire/setup-wsl@v3.1.3
      with:
        distribution: Ubuntu-22.04
    - shell: wsl-bash {0}
      run: |
        ls -l /mnt/
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4.4.3
      if: ${{ always() }}
      with:
        name: tests-win64-wsl2-artifacts
        path: |
          ./**/*.log

