name: test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch:
        description: "ref branch for this workflow"
        default: "master"
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  test-windows-wsl-x64:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.1
      with:
        ref: ${{ inputs.branch }}
    - name: Setup WSL
      uses: Vampire/setup-wsl@v3.1.3
      with:
        distribution: Ubuntu-22.04
    - shell: wsl-bash {0}
      run: |
        # Build, Test units and Integration tests
        win_workspace="${{ github.workspace }}"
        linux_workspace="/mnt/$(echo "${win_workspace}" | tr -d ':'  | tr '\\' '/' | tr '[:upper:]' '[:lower:]')"
        cd "${linux_workspace}"
    - shell: wsl-bash {0}
      run: bin/install_prerequisites_ubuntu.sh
    - shell: wsl-bash {0}
      run: |
        echo "::group::Install python3 venv"
          bin/install_python3_venv.sh
          export PATH=/tmp/hurl-python3-venv/bin:$PATH
          which python3
          python3 --version
          pip --version
        echo "::endgroup::"
        echo "::group::Install Rust"
          bin/install_rust.sh
        echo "::endgroup::"
        echo "::group::Environment"
          bin/environment.sh
        echo "::endgroup::"
        echo "::group::Tests"
          bin/test/test.sh
        echo "::endgroup::"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4.4.3
      if: ${{ always() }}
      with:
        name: tests-win64-wsl-artifacts
        path: |
          ./**/*.log

